spring:
  application:
    name: resident-management-service
  datasource:
    url: jdbc:h2:mem:ams_resident_db;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 86400000

server:
  port: 8080
